name: Codacy Coverage

on:
  push:
    branches: [ master   ]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    strategy:
      matrix:
        node-version: [12.x]
    steps:  
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test-coverage
      - run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/clover.xml -t ${{ secrets.CODACY_PROJECT_TOKEN }}